INSERT INTO users (name, age, created_at, updated_at) VALUES
('Alice', 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bob', 25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Charlie', 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO users (name, age, created_at, updated_at) VALUES
('Min', 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Jane', 28, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('John', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

COMMIT;