from airflow.sdk import DAG, task
from airflow.providers.mysql.hooks.mysql import MySqlHook
from airflow.providers.postgres.hooks.postgres import PostgresHook
from airflow.providers.amazon.aws.hooks.s3 import S3Hook
from pendulum import datetime
import polars as pl
import os

BUCKET_NAME = "airflow-demo" # bucket 명에 "_"(underscore)를 사용해서는 안됨에 유의
MYSQL_OUTPUT_DIR = "/tmp/data/mysql"
POSTGRES_OUTPUT_DIR = "/tmp/data/postgres"
FILE_FORMAT = "parquet" # csv
LOCAL_FILENAME = "users.parquet" # users.csv
S3_PREFIX = "db_users"
POSTGRES_SCHEMA = "stage"

""" Task Dependency
[create_bucket(), create_local_dir] -> extract_from_mysql() -> load_to_s3() -> extract_from_s3() -> create_postgres_table() -> insert_to_postgres
[S3 버킷생성, 임시 디렉토리 생성] -> mysql에서 로컬로 파일 추출] -> 추출된 파일을 s3 upload -> s3에서 파일 추출 -> postgres에 users 테이블 생성 -> 파일을 users에 insert
"""
with DAG(
    dag_id="mysql_s3_postgres_load_01",
    start_date=datetime(2026, 1, 1, tz="Asia/Seoul"),
    schedule=None,
    catchup=False,
    tags=["operator_hook", "sql", "s3"],
) as dag:
    
    ### 지정된 이름으로 bucket 생성
    @task
    def create_bucket(bucket_name):
        hook = S3Hook(aws_conn_id="minio_conn")

        if hook.check_for_bucket(bucket_name=bucket_name):
            print(f"#### Bucket already exists: {bucket_name}")
        else:
            hook.create_bucket(bucket_name=bucket_name)
            print(f"#### Bucket created: {bucket_name}")

    # 1-1 S3 Bucket 생성
    run_create_bucket = create_bucket(bucket_name=BUCKET_NAME)
    
    ### MySQL용, PostgreSQL용 임시 로컬 디렉토리 생성
    @task
    def create_local_dirs(dir_list: list[str]):
        for dir_name in dir_list:
            os.makedirs(dir_name, exist_ok=True)
    
    # 1-2 MySQL용, PostgreSQL용 로컬 폴더 생성(/tmp/data/mysql, /tmp/data/postgres)
    run_create_dirs = create_local_dirs(dir_list=[MYSQL_OUTPUT_DIR, POSTGRES_OUTPUT_DIR])
        
    ### MySQL에서 users 테이블의 모든 데이터를 지정된 file명과 format 형식을 가지는 local 파일로 추출
    @task
    def extract_from_mysql(output_filepath, file_format):
        hook = MySqlHook(mysql_conn_id="mysql_ecom_conn")
        raw_conn_uri = hook.get_uri()
        print(f"#### uri:{raw_conn_uri}, type:{type(raw_conn_uri)}")
        # connectorx는 connection에 있는 추가 필드인 charset=...를 해석하지 못함
        conn_uri = raw_conn_uri.split('?')[0]

        # read_database_uri()는 기본적으로 connectorx를 엔진으로 사용하여 connection용 uri 문자열을 입력 받음.
        polas_df = pl.read_database_uri(
            query="select * from users",
            uri=conn_uri
        )
        
        # file_format에 따라 csv 또는 parquet으로 설정
        if file_format == "csv":
            polas_df.write_csv(output_filepath)
        elif file_format == "parquet":
            polas_df.write_parquet(output_filepath)
    
        return output_filepath
    
    # 2. mysql에서 로컬로 파일 추출
    mysql_output_path=f"{MYSQL_OUTPUT_DIR}/{LOCAL_FILENAME}"
    run_extract_mysql = extract_from_mysql(output_filepath=mysql_output_path, 
                                           file_format=FILE_FORMAT)
    
    ### full path를 가지는 local 파일을 S3 지정된 bucket과 object key로 Upload
    @task
    def load_to_s3(local_filepath, bucket_name, object_key):
        hook = S3Hook(aws_conn_id="minio_conn")
        
        hook.load_file(
            filename=local_filepath, # filename은 로컬 파일명
            key=object_key, # bucket내의 object key값
            bucket_name=bucket_name, # 로컬 파일을 upload할 Object Storage 버킷명
            replace=True, #해당 object가 이미 존재할 경우 replace 여부. False이면 기존에 Object가 있을 경우 오류 발생.
        )

        print(f"#### Uploaded {local_filepath} to s3://{bucket_name}/{object_key}")

    # 3. 추출된 파일을 s3 upload
    object_key = f"{S3_PREFIX}/{LOCAL_FILENAME}"
    run_upload = load_to_s3(local_filepath=mysql_output_path, 
                            bucket_name=BUCKET_NAME, object_key=object_key)

    ### PostgreSQL Insert를 위해, S3에 있는 파일을 지정된 local 파일로 download
    @task
    def extract_from_s3(bucket_name, object_key, download_dir, local_filename):
        s3_hook = S3Hook(aws_conn_id="minio_conn")
        
        # S3Hook의 download_file()은 지정된 bucket명, key를 가지는 Object를 download 수행
        # download_file()은 로컬 파일이 이미 있으면 덮어쓰지 않고 안정성을 이유로 오류를 발생 시킴. 
        # 기 생성된 동일명 로컬 파일이 있다면 미리 삭제
        local_fullpath = f"{download_dir}/{local_filename}"
        if os.path.exists(local_fullpath):
            os.remove(local_fullpath)

        # download_file()의 local_path는 download 시도할 디렉토리로 인지함. 파일명을 기술하면 해당 파일명으로 디렉토리를 만들어 버림
        # local_path에는 디렉토리까지, preserve_file_name=True, use_autogenerated_subdir=False로 설정하여 download 수행. 
        downloaded_path = s3_hook.download_file(key=object_key, bucket_name=bucket_name, 
                                                local_path=download_dir, preserve_file_name=True,
                                                use_autogenerated_subdir=False)
        
        return downloaded_path
    
    # 4. PostgreSQL입력을 위해서 s3에서 파일 추출
    run_extract_from_s3 = extract_from_s3(bucket_name=BUCKET_NAME, 
                                          object_key=object_key, download_dir=POSTGRES_OUTPUT_DIR,
                                          local_filename=LOCAL_FILENAME)
    
    ### PostgreSQL에 Drop & Create 테이블 수행
    @task
    def create_postgres_table():
        hook = PostgresHook(postgres_conn_id="postgres_delivery_conn")

        sql=f"""
        -- 기존에 users 테이블이 있으면 drop table 수행
        DROP TABLE IF EXISTS {POSTGRES_SCHEMA}.users_from_mysql;

        /* users 테이블이 없으면 users 테이블 생성 */
        CREATE TABLE IF NOT EXISTS {POSTGRES_SCHEMA}.users_from_mysql (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(255),
        age INT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        """

        hook.run(sql=sql)

    # 5. postgres에 users 테이블 생성
    run_create_table = create_postgres_table()

    # local 파일을 Polars를 이용하여 PostgreSQL에 적재
    @task
    def insert_to_postgres(load_filepath, file_format="parquet"):
        # load_filepath로 지정된 파일을 Polars DataFrame으로 읽어 들임
        if file_format == "parquet":
            polas_df = pl.read_parquet(load_filepath)
        else:
            polas_df = pl.read_csv(load_filepath)

        # Polars의 write_database를 이용하여 Postgres 적재. sqlalchemy engine 사용
        pg_hook = PostgresHook(postgres_conn_id="postgres_delivery_conn", 
                               options=f"-c search_path={POSTGRES_SCHEMA}")
        
        sql_alchemy_engine = pg_hook.get_sqlalchemy_engine()
        polas_df.write_database(
            table_name="users_from_mysql",
            connection=sql_alchemy_engine,
            engine="sqlalchemy",  # sqlalchemy 엔진 지정.
            if_table_exists="append" # if_table_exists는 default가 fail(만약 기존 테이블이 있으면 오류 발생). append로 설정. 
        )

        # Hook 생성 시 search_path로 stage schema 설정하더라도 sqlalchemy와 같은 python 엔진과 다르게
        # adbc 엔진은 이를 감안하지 않고 public schema를 사용함. 반드시 table_name에 schema 명 stage 기재 필요. 
        # conn_uri = pg_hook.get_uri()
        # polas_df.write_database(
        #     table_name=f"{POSTGRES_SCHEMA}.users_from_mysql",
        #     connection=conn_uri,
        #     engine="adbc",  # ADBC 엔진 지정
        #     if_table_exists="append" # if_table_exists는 default가 fail(만약 기존 테이블이 있으면 오류 발생). append로 설정. 
        # )

    # 6. 파일을 users에 insert
    postgres_load_path = f"{POSTGRES_OUTPUT_DIR}/{LOCAL_FILENAME}" 
    run_insert_to_postgres = insert_to_postgres(load_filepath=postgres_load_path, 
                                                file_format=FILE_FORMAT)  
    
    # 아래는 taskflow간 dependency 설정. 
    [run_create_bucket, run_create_dirs] >> run_extract_mysql >> run_upload >> run_extract_from_s3 \
                                         >> run_create_table >> run_insert_to_postgres
