from airflow.sdk import DAG, task
from airflow.providers.common.sql.operators.sql import SQLExecuteQueryOperator
from airflow.providers.postgres.hooks.postgres import PostgresHook
from pendulum import datetime
import pandas as pd
import os

OUTPUT_DIR = "/tmp/postgres_load"
# 작업 수행 schema 설정
SCHEMA = "stage"

"""
Task 수행시 별도의 search_path를 지정하는 방식
1. airflow connection 생성 시 extra 필드에 { "options": "-c search_path=스키마명"} 설정
2. hook에 options 설정
 2-1. SQLExecuteQueryOperator에 hook_params 인자 적용.  hook_params={"options": f"-c search_path=스키마명"}
 2-2. PostgresHook 생성 시 추가 인자 적용. options="-c search_path=스키마명"
"""

with DAG(
    dag_id="postgres_op_hook_02",
    start_date=datetime(2026, 1, 1, tz="Asia/Seoul"),
    schedule=None,
    catchup=False,
    tags=["operator_hook", "sql"],
) as dag:

    create_table_op = SQLExecuteQueryOperator(
        task_id="create_users_table",
        conn_id="postgres_delivery_conn",
        sql=f"""
        -- 기존에 users 테이블이 있으면 drop table 수행
        DROP TABLE IF EXISTS users;

        /* users 테이블이 없으면 users 테이블 생성 */
        CREATE TABLE IF NOT EXISTS users (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(255),
        age INT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        """, 
        hook_params={"options": f"-c search_path={SCHEMA}"}
    )

    @task
    def insert_users():
        hook = PostgresHook(postgres_conn_id="postgres_delivery_conn",
                            options=f"-c search_path={SCHEMA}"
                            )

        sql=f"""
        INSERT INTO users (name, age) VALUES
        ('Alice', 30),
        ('Bob', 25),
        ('Charlie', 40);

        INSERT INTO users (name, age) VALUES
        ('Min', 50),
        ('Jane', 28),
        ('John', 20);

        COMMIT;
        """

        hook.run(sql=sql)


    @task
    def select_and_write_csv():
        hook = PostgresHook(postgres_conn_id="postgres_delivery_conn",
                            options=f"-c search_path={SCHEMA}"
                            )
        # 아래는 sql내에서 search_path 를 부여
        sql = """
        

        SELECT id, name, age, created_at, updated_at
        FROM users;
        """

        # MysqlHook은 pandas와 잘 통합되어 get_pandas_df(sql)을 수행하면 sql을 수행 후 결과를 pandas로 반환
        # df = hook.get_pandas_df(sql)
        # 또는 아래와 같이 MysqlHook에서 db connection 객체를 가져 온 뒤,
        # pandas의 read_sql()에 수행 sql와 db connection 객체를 입력 하여, 
        # 해당 sql를 수행하고 결과를 DataFrame에 반환함. 대용량 Select시 메모리 과다 소모 유의
        conn = hook.get_conn()   # DB-API connection
        df = pd.read_sql(sql, conn)

        os.makedirs(OUTPUT_DIR, exist_ok=True)
        file_path = f"{OUTPUT_DIR}/users_postgres_02.csv"
        df.to_csv(file_path, index=False)

        # hook.get_conn()을 수행하였으면 connection을 close 시킴
        conn.close()

        print(f"CSV written to {file_path}")
        return file_path

    create_table_op >> insert_users() >> select_and_write_csv()
