1. serialization 관련 메타 테이블 조회
/* serialization 관련 메타 테이블 조회 */ 
create temp table dag_temp
as
select a.* 
from dag a 
where a.dag_id in (select x.dag_id from dag_tag x where name='fundamental')
;

select * from serialized_dag a where dag_id in (select dag_id from dag_temp);

select * from dag_code where dag_id in (select dag_id from dag_temp);

select * from dag_version where dag_id in (select dag_id from dag_temp);

2. generate_orders_data 프로시저
/************************************************** 
* 아래는 Postgres DB의 stage schema에서 orders 테이블을 Drop/Create 후 입력 받은 시작 시간과 종료 시간 동안 
3분 주기로 random 데이터를 입력하는 프로시저

* 반드시 stage schema에서 수행. 수행은 아래와 같음
-- 2026년 2월 1일 0시 0분 0초부터 2월 2일 23시 59분 59초까지 이틀간 3분 간격 데이터 생성
CALL generate_orders_data('2026-02-01 00:00:00', '2026-02-02 23:59:59');

-- 생성된 데이터 확인
SELECT COUNT(*) FROM orders;

SELECT 
    DATE(order_dt) AS order_date, 
    COUNT(*) AS daily_order_count,
    SUM(amount) AS daily_revenue
FROM orders
GROUP BY DATE(order_dt)
ORDER BY order_date;
***************************************************/

CREATE OR REPLACE PROCEDURE stage.generate_orders_data(
    p_start_dt TIMESTAMP,
    p_end_dt TIMESTAMP
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_current_dt TIMESTAMP;
    v_user_id BIGINT;
    v_amount DECIMAL(10,2);
BEGIN
    -- 0. 스키마 생성
    CREATE SCHEMA IF NOT EXISTS stage;

    -- 1. 랜덤 시드 고정
    PERFORM setseed(0.5);

    -- 2. 테이블 초기화
    DROP TABLE IF EXISTS stage.orders;

    CREATE TABLE stage.orders (
        order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL,
        order_dt TIMESTAMP,
        amount DECIMAL(10,2),
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    -- 3. 데이터 생성 루프
    v_current_dt := p_start_dt;

    WHILE v_current_dt < p_end_dt LOOP
        v_user_id := FLOOR(RANDOM() * 10000 + 1);
        v_amount := ROUND((RANDOM() * 490 + 10)::NUMERIC, 2);
        
        INSERT INTO stage.orders (
            user_id, 
            order_dt, 
            amount, 
            created_at, 
            updated_at
        ) 
        VALUES (
            v_user_id, 
            v_current_dt, 
            v_amount, 
            v_current_dt, 
            v_current_dt
        );

        v_current_dt := v_current_dt + INTERVAL '3 minutes';
    END LOOP;

    -- 4. 인덱스 생성 (루프 종료 후 수행)
    CREATE INDEX orders_order_dt_idx ON stage.orders(order_dt);
    CREATE INDEX orders_created_at_idx ON stage.orders(created_at);
    CREATE INDEX orders_updated_at_idx ON stage.orders(updated_at);

END;
$$;

3. orders 테이블의 TIMESTAMP 컬럼들을 TIMEZONE을 반영한 TIMESTAMPTZ 컬럼들로 변환하여 orders_tz 테이블 생성 
/************************************************** 
stage의 orders 테이블의 TIMESTAMP 컬럼들을 TIMEZONE을 반영한
TIMESTAMPTZ 컬럼들로 변환하여 orders_tz 테이블 생성. 
***************************************************/

DROP TABLE if exists stage.orders_tz;

CREATE TABLE if not exists stage.orders_tz (
        order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL,
        order_dt TIMESTAMPTZ,
        amount DECIMAL(10,2),
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

insert into stage.orders_tz
select *from stage.orders;

commit;